### PR TITLE
Generate certificates via a container

### PR DESCRIPTION
**Pull request by Aerzas**
To ease certificates generation on different OS, I propose to do it via container. I've created a separated repository for the docker image as it could be used on other projects.

Tested on ArchLinux and MacOS.

**Important changes**
- Certificate is no more named `docker.rootCA.crt` but `docker.test.rootCA.crt` to avoid possible extension conflicts.

**External links**
- https://github.com/liip/docker-ssl-keygen
- https://hub.docker.com/r/liip/ssl-keygen

### CODE REVIEW

**Comment by chregu** [comment]
You did know about this PR #1? Is something of the stuff there also in this PR?
Especially the possibility for having multiple alternate DNS entries?

**Comment by Aerzas** [comment]
Yes I know of it and didn't implement the features you propose to not "steel" your ideas, I focused only on the generation via a container.

If you want I can start integrating PR #1 within this one or the contrary.

**Comment by chregu** [comment]
Looking more closely at it, i'd say we just merge this and then try to rebase and "fix" #1

**Comment by Aerzas** [comment]
Let's do that

**Pull request merged**
