### PR TITLE
Enable HTTP, prefix container names, make http(s) port configurable

### PR DESCRIPTION
**Pull request by chregu**
- enables http and not only https for traefik. Some projects may be happy with just http (but you can reenable the redirect per container with the label `traefik.frontend.headers.SSLRedirect=true`
- adds .env options for the http and https port
- prefixes container names with `pontsun_` to make them more unique.

### CODE REVIEW

**Comment by OdyX** [comment]
What's the use case to have ports other than 80 / 443 for HTTP/HTTPS ?

**Comment by dbu** [comment]
my system is running a local apache on port 80. i could shut that down before starting working on a project, but it is annoying. i rather run the docker thingy on port 8080 or similar.

**Comment by chregu** [comment]
What dbu said. Others have the same issue

**Review by Aerzas — APPROVED** [review]
Thank you for the PR, it sure makes sense to open to HTTP and custom ports.

**Pull request merged**
